spring:
  application:
    name: gateway
  profiles:
    active: prod
  cloud:
    gateway:
      routes:
        - id: auth-service_route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: user-service_route
          uri: lb://user-service
          predicates:
            - Path=/user/**

        - id: property-service_route
          uri: lb://property-service
          predicates:
            - Path=/property/**

        - id: image-service_route
          uri: lb://image-service
          predicates:
            - Path=/image/**

        - id: document-service_route
          uri: lb://document-service
          predicates:
            - Path=/document/**

    discovery:
      locator:
        enabled: true
        lower-case-service-id: true
eureka:
  client:
    instance:
      preferIpAddress: true

server:
  port: 8888